language: python

os:
  - linux

python:
  - "3.6"

# Command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip python-dev build-essential cmake libopenblas-dev liblapack-dev --no-install-recommends

# Navigate to src folder before running the script
before_script:
  - cd src

# Command to run tests
script:
  - make test